<?php
$googlehelper = $this->helper('Magecomp\Googlelangtranslator\Helper\Data');
$isenabled = $googlehelper->isEnabled();
if($isenabled) :
    $lanselected = $googlehelper->SelectLanguage();
    $layoutselected = $googlehelper->SelectLayout();
    $bashlanguage = substr($googlehelper->BashLanguage(), 0, 2);
    $layouthtml = 'layout: google.translate.TranslateElement.InlineLayout.'.$layoutselected; ?>

    <div id="google_translate_element" style="float: right;"></div>
        <script type="text/javascript">
            function googleTranslateElementInit()
            {
                new google.translate.TranslateElement(
                    {
                        pageLanguage: 'zu',
                        includedLanguages: '<?php echo $lanselected; ?>',
                        <?php echo $layouthtml; ?>
                    },
                    'google_translate_element');
            }
        </script>
        <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        <style type="text/css">
            body { top : 0 !important;}
            .goog-te-banner-frame.skiptranslate {
                display: none !important;
            }
            .goog-te-gadget-simple{
                position: absolute !important;
                top:10px;
            }
            .goog-te-gadget{background: #826fc9 !important;}
            .action.skip:not(:focus)
            {
                border: 0;
                clip: rect(0, 0, 0, 0);
                height: 0px;
                margin-top: 2px;
                overflow: hidden;
                padding: 4px;
                position: relative;
                width: 0px;
                display: inline-table;
                font-size: 7px;
                display: none;
            }
            .goog-te-combo{width: auto !important;  border-radius: 2px;  margin-left: 10px !important;}
            .panel.wrapper{
                height: 65px;
            }
            .VIpgJd-ZVi9od-l4eHX-hSRGPd, .VIpgJd-ZVi9od-l4eHX-hSRGPd:link{    font-size: 12px !important; font-weight: 100 !important; color: #fff !important;}
            .VIpgJd-ZVi9od-ORHb{width: auto !important;}
        </style>
<?php endif; ?>