<!-- cart pg -->
  <section class="cart_pg">
    <div class="main_container img_skeleton skeleton">
      <ul class="product_checkout_progress_bar_wrap hide-div">
        <li class="product_checkout_progress_bar_item ">
          <div class="product_checkout_progress_bar_item_label active">1. Cart</div>
          <div class="product_checkout_progress_bar active"></div>
        </li>
        <li class="product_checkout_progress_bar_item">
          <div class="product_checkout_progress_bar_item_label">2. Shipping Details</div>
          <div class="product_checkout_progress_bar"></div>
        </li>
        <li class="product_checkout_progress_bar_item">
          <div class="product_checkout_progress_bar_item_label">3. Payment</div>
          <div class="product_checkout_progress_bar"></div>
        </li>
      </ul>

      <div class="cart_main_split">
        <ul class="cart_items_wrap">
          <li class="cart_item_wrap hide-div">
            <div class="cart_item_img">
              <img src="assets/img/thumb3.png" />
            </div>
            <div class="cart_item_right_wrap">
              <div class="cart_item_product_details_wrap">
                <div class="cart_product_name">ITEM 3986
                </div>
                <div class="cart_product_variant_name">
                  Black / Prescription
                </div>
                <div class="cart_product_price_wrap">
                  <div class="cart_product_actual_price">
                    AED 49,00
                  </div>
                  <div class="cart_product_sales_price">AED 20.00
                  </div>
                </div>
              </div>
              <div class="cart_item_btns_wrap">
                <div class="quantity">
                  <button class="quantity__minus">-</button>
                  <input name="quantity" type="text" class="quantity__input" value="1">
                  <button class="quantity__plus">+</button>
                </div>
                <div class="cart_item_delete_btn_wrap">
                  <button class="cart_item_delete_btn"><img src="assets/img/delete.svg" /></button>
                </div>
              </div>

            </div>


          </li>
          <li class="cart_item_wrap hide-div">
            <div class="cart_item_img">
              <img src="assets/img/thumb3.png" />
            </div>
            <div class="cart_item_right_wrap">
              <div class="cart_item_product_details_wrap">
                <div class="cart_product_name">ITEM 3986
                </div>
                <div class="cart_product_variant_name">
                  Black / Prescription
                </div>
                <div class="cart_product_price_wrap">
                  <div class="cart_product_actual_price">
                    AED 49,00
                  </div>
                  <div class="cart_product_sales_price">AED 20.00
                  </div>
                </div>
              </div>
              <div class="cart_item_btns_wrap">
                <div class="quantity">
                  <button class="quantity__minus">-</button>
                  <input name="quantity" type="text" class="quantity__input" value="1">
                  <button class="quantity__plus">+</button>
                </div>
                <div class="cart_item_delete_btn_wrap">
                  <button class="cart_item_delete_btn"><img src="assets/img/delete.svg" /></button>
                </div>
              </div>

            </div>


          </li>
        </ul>
        <div class="cart_order_summary_wrap hide-div">
          <h6 class="order_summary_title">Order summary</h6>
          <div class="cart_coupon_apply_wrap">
            <input class="cart_coupon_apply_input" name="coupon" type="text" placeholder="Add discount coupon">
            <button class="cart_coupon_apply_btn"><img src="assets/img/carrow.svg" /></button>
          </div>
          <ul class="cart_summary_wrap">
            <li class="cart_summary_item">
              <div class="cart_summary_label">SUBTOTAL</div>
              <div class="cart_summary_wrap_value">$ 65,00</div>
            </li>
            <li class="cart_summary_item">
              <div class="cart_summary_label">SHIPPING </div>
              <div class="cart_summary_wrap_value">FREE</div>
            </li>
            <li class="cart_summary_item">
              <div class="cart_summary_label">DISCOUNT</div>
              <div class="cart_summary_discount_value cart_summary_wrap_value ">-$25</div>
            </li>
            <li class="cart_summary_item">
              <div class="cart_summary_total_label cart_summary_label ">SUBTOTAL</div>
              <div class="cart_summary_total_value cart_summary_wrap_value">$ 65,00</div>
            </li>
          </ul>
          <button onClick="location.href='checkout.html'" class="primary_btn">Proceed to checkout</button>

        </div>


      </div>

    </div>
  </section>