<!-- my account -->
  <section class="my_account_pg">
    <div class="main_container img_skeleton skeleton">
      <div class="">
        <div class="mob_dashboard_select hide-div">
          <select class="form-select" aria-label="Default select example" onchange="location = this.value;">
            <option value="my-account.html" selected>dashboard</option>
            <option value="orders.html">orders </option>
            <option value="addresses.html">Addresses popular</option>
            <option value="account-details.html">Account details </option>
            <option value="">Logout</option>

          </select>
        </div>

        <div class="dashboard_content hide-div">
          <p>Hello John (not John? <a href="">Log out</a>)</p>
          <p>From your account dashboard you can view your <a href="orders.html">recent orders</a> , manage your <a href="addresses.html">shipping and billing addresses</a> , and edit your <a href="account-details.html">password and account
              details.</a> </p>


        </div>


      </div>
    </div>
  </section>