<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
	<section class="reset_password_pg">
		<div class="main_container img_skeleton skeleton">
			<div class="reset_password_wrap hide-div">
				<h3 class="reset_password_title ">Have you Forgotten Your Password ?</h3>
				<p class="reset_password__desc ">If you've forgotten your password, enter your e-mail address and we'll send you an e-mail </p>
				<form class="form password forget rest_password_form" action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>" method="post" id="form-validate" data-mage-init='{"validation":{}}'>
					<fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
						<div class="field email required">
							<div class="control">
								<input type="email" name="email" alt="email" id="email_address" class="input-text" placeholder="Email" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}"> </div>
						</div>
						<?php //$block->getChildHtml('form_additional_info') ?>
					</fieldset>
					<div class="actions-toolbar">
						<div class="primary">
							<button type="submit" class="action submit primary primary_btn w_100"><span><?= $block->escapeHtml(__('RESET PASSWORD')) ?></span></button>
						</div>
						<div class="secondary"> <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a> </div>
					</div>
				</form>
			</div>
		</div>
	</section>
	<script type="text/x-magento-init"> { "*": { "Magento_Customer/js/block-submit-on-send": { "formId": "form-validate" } } } </script>
<script>
require(["jquery"], function ($) {
    // Reload captcha when page loaded
    $(window).bind("load", function() {
        // Use setTimeout to trigger captcha reload. 
        $(".action.captcha-reload").trigger("click");
    });
});
</script>