<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<section class="my_account_pg">
<div class="block block-customer-login main_container img_skeleton skeleton">
    <div class="block-content login_wrap login_wrap" aria-labelledby="block-customer-login-heading">
		<h3 class="login_title hide-text">My account</h3>
		<ul class="login_tab_label_wrap hide-div">
        <li class="login_tab_label_item "><a href="https://magento-920116-4739515.cloudwaysapps.com/customer/account/create/">Register</a></li>
          <li class="login_tab_label_item active"><a href="https://magento-920116-4739515.cloudwaysapps.com/customer/account/login">Sign in</a></li>
        </ul>
		<div class="login_form_wrap hide-div">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>

            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field email required">
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}" placeholder="Email">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" type="password"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}" placeholder="Password">
                    </div>
                </div>
				<div class="field choice login_form_checkbox" data-bind="scope: 'showPassword'">
				  <!-- ko template: getTemplate() --><!-- /ko -->
				</div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="primary_btn w_100 action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div></br>
					<div class="primary" style="display:none"><button type="submit" class="primary_btn w_100" name="send" id="send3"><a class="action remind" href="https://magento-920116-4739515.cloudwaysapps.com/customer/account/create/"><span><?= $block->escapeHtml(__('Sign Up')) ?></span></a></button></div>
					<p class="login_form_forgot_password">Have you forgotten your password? <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Click here')) ?></span></a></p>
				</div>
            </fieldset>
        </form>
		</div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                },
                "Magento_Ui/js/core/app": {
                    "components": {
                        "showPassword": {
                            "component": "Magento_Customer/js/show-password",
                            "passwordSelector": "#pass"
                        }
                    }
                }
            }
        }
    </script>
</div>
</section>