
<?php
   /**
    * Copyright © 2016 Magento. All rights reserved.
    * See COPYING.txt for license details.
    */
   
   // @codingStandardsIgnoreFile
   
   /**
    * @var \Magento\Theme\Block\Html\Header $block
    */
   
   ?>   
<!-- footer -->
<!-- Google tag (gtag.js) -->
<!--<script async src="https://www.googletagmanager.com/gtag/js?id=G-EP00T9KLXY"></script>-->
<script>
  window.dataLayer = window.dataLayer || [];
 /* function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EP00T9KLXY');*/
</script>

<hr class="footer_hr">
<footer class="footer">
   <div class="main_container">
      <ul class="footer_main_child">
		 <li class="footer_contact_wrapper">
        <?php 
			echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('basari_footer_left')->toHtml();
		?>
		</li>
		<li class="footer_menu_wrapper">
		  <ul class="footer_menu_list_wrap">
			<div class="footer_list_heading">
				<h6 class="footer_menu_list_heading"><b>Customer care</b></h6>
				<span><i class="fas fa-chevron-down"></i></span>
			</div>
			<div class="footer_list_items">
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/faq">FAQ</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/contact">Contact us</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/customer/account/login">My account</a>
				</li>
				<li class="footer_menu_list_item"><a href="https://magento-920116-4739515.cloudwaysapps.com/customer/account/login">Login</a></li>
				<li class="footer_menu_list_item"><a href="https://magento-920116-4739515.cloudwaysapps.com/customer/account/create/">Register</a></li>
			</div>
		  </ul>
		  <ul class="footer_menu_list_wrap">
			<div class="footer_list_heading">
				<h6 class="footer_menu_list_heading"><b>Categories</b></h6>
				<span><i class="fas fa-chevron-down"></i></span>
			</div>
			<div class="footer_list_items">
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/sunglasses.html">Sunglasses</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/frames.html">Frames</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/contact-lenses/color-contact-lenses.html">Color contact Lenses</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/contact-lenses/clear-contact-lenses.html">Clear contact Lenses</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/bluelight.html">Bluelight glasses</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/accessories.html">Accessories </a>
				</li>
			</div>
		  </ul>
		  <ul class="footer_menu_list_wrap">
			<div class="footer_list_heading">
				<h6 class="footer_menu_list_heading"><b>Top Links</b></h6>
				<span><i class="fas fa-chevron-down"></i></span>
			</div>
			<div class="footer_list_items">
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/wishlist/">Wishlist</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/offers.html">Offers</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/brand">Brands</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/service">Driving eye test</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/lens-repair">Eyewear repairing</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/lens-solutions.html">Contact lens solution</a>
				</li>
			</div>
			<!-- <li class="footer_menu_list_item">
			  <a href="https://magento-920116-4739515.cloudwaysapps.com/eye-glasses/top-brand-eyeglasses/rayban-eyeglasses.html">Rayban</a>
			</li>
			<li class="footer_menu_list_item">
			  <a href="https://magento-920116-4739515.cloudwaysapps.com/eye-glasses/top-brand-eyeglasses/rayban-eyeglasses.html">Oakley</a>
			</li>
			<li class="footer_menu_list_item">
			  <a href="https://magento-920116-4739515.cloudwaysapps.com/eye-glasses/top-brand-eyeglasses/rayban-eyeglasses.html">Gucci</a>
			</li>
			<li class="footer_menu_list_item">
			  <a href="https://magento-920116-4739515.cloudwaysapps.com/eye-glasses/top-brand-eyeglasses/rayban-eyeglasses.html">Chanel</a>
			</li>
			<li class="footer_menu_list_item">
			  <a href="https://magento-920116-4739515.cloudwaysapps.com/eye-glasses/top-brand-eyeglasses/rayban-eyeglasses.html">Mont blanc</a>
			</li> -->
		  </ul>
		  <ul class="footer_menu_list_wrap">
			<div class="footer_list_heading">
				<h6 class="footer_menu_list_heading"><b>About Basari</b></h6>
				<span><i class="fas fa-chevron-down"></i></span>
			</div>
			<div class="footer_list_items">
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/about-us">About us</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/term-and-condition">Terms &amp; Condition</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/privacy-policy">Privacy policy</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/return-and-refund-policy">Return &amp; refund policy</a>
				</li>
				<li class="footer_menu_list_item">
				  <a href="https://magento-920116-4739515.cloudwaysapps.com/shiping-and-delivery">Shipping &amp; Delivery</a>
				</li>
			</div>
		  </ul>
		</li>
		<?php 
			//echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('basari_footer_right')->toHtml();
		?>
		
      </ul>
      <hr class="footer_hr">
      <div class="footer_second_child">
         <div class="footer_second_child_left">
            <div class="footer_newsletter_wrap">
            	<?php echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml() ?>
            </div>
            <div class="footer_social_wrap">
               <div class="footer_social_label">Follow us</div>
               <ul class="footer_social_items_wrap">
                  <li class="footer_social_item">
                     <a href="https://www.facebook.com/basariopticalsdubai" target="_blank"><i class="fab fa-facebook-f"></i></a>
                  </li>
                  <li class="footer_social_item">
                     <a href="https://www.instagram.com/basariopticals/" target="_blank"><i class="fab fa-instagram"></i></a>
                  </li>
                  <li class="footer_social_item">
                     <a href="https://www.youtube.com/channel/UCRhJL10IagLktqaHWjS-p7g" target="_blank"><i class="fab fa-youtube"></i></a>
                  </li>
				  <li class="footer_social_item">
                     <a href="https://twitter.com/basariopticals?lang=en" target="_blank"><i class="fab fa-twitter"></i></a>
                  </li>
				  <li class="footer_social_item">
                     <a href="https://www.linkedin.com/company/basariopticals/" target="_blank"><i class="fab fa-linkedin"></i></a>
                  </li>
               </ul>
            </div>
         </div>
         <div class="footer_second_child_right">
			<div class="footer_whatsapp">
				<a href="https://wa.me/971526971100" target="_blank">
				  <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/wats.png" />
				</a>
            </div>
            <div class="footer_payment_acceptance_wrap">
               <div class="footer_payment_acceptance_label">We accept</div>
               <ul class="footer_payment_acceptance_item_wrap">
                  <li class="footer_payment_acceptance_item">
                     <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/visa.png" />
                  </li>
                  <li class="footer_payment_acceptance_item">
                     <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/master.png" />
                  </li>
				 		<li class="footer_payment_acceptance_item" style="width: 60px;">
                     <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/applepay.png" />
                  </li>
                  <li class="footer_payment_acceptance_item" style="margin-left: 10px;width: 60px;">
	                <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/tabby-badge.png" />
	              </li>
	              <li class="footer_payment_acceptance_item" style="width: 60px;">
	                <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/samsung.png" />
	              </li>
	              <li class="footer_payment_acceptance_item" style="width: 60px;">
	                <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/cod.png" />
	              </li>
               </ul>
            </div>
         </div>
      </div>
   </div>
   <div class="footer_bar">
      <div class="copyright">©Basari Opticals All Rights Reserved.</div>
      <div class="developed_by"><a href="https://acuteangle.io/">Designed with Love by Acute Angle</a></div>
   </div>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
        (function(){
            var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
            s1.async=true;
            s1.src='https://embed.tawk.to/63de480fc2f1ac1e20316255/1goe4ivnh';
            s1.charset='UTF-8';
            s1.setAttribute('crossorigin','*');
            s0.parentNode.insertBefore(s1,s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
	<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "mnmknhzlmo");
</script>
	
</footer>
