<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
        echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('delivery_time')->toHtml();
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>

<?php if ($block->shouldRenderQuantity()) : ?>
	<div class="product_pg_qty hide-div">
            <label class="label variant_label" for="qty"><span><?= $block->escapeHtml(__('Quantity')) ?></span></label>
            <div id="custom-qty" class="quantity control qty-control" data-bind="scope: 'qty-counter'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <script type="text/x-magento-init">
                    {
                        "#custom-qty": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "qty-counter": {
                                        "component": "qty-counter",
                                        "config": {
                                            "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                            "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                        }
                                    }
                                 }
                            }
                        }
                    }
                </script>
            </div>
        </div>	
<?php endif; ?>
<div class="product_btns_wrap hide-div actions">
			<button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="add_to_cart_btn action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?php //$block->getChildHtml('', true) ?>
            <button class="product_wishlist_btn ml">wishlist item</button>
          </div>
<?php endif; ?>
	<ul class="product_safety_protocol_wrap hide-div">
            <li class="product_safety_protocol">
              <span class="product_safety_protocol_icon">
                <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/pficon.svg" />
              </span>Secure payments
            </li>
            <li class="product_safety_protocol">
              <span class="product_safety_protocol_icon">
                <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/pficon.svg" />
              </span>Safe shopping
            </li>
            <li class="product_safety_protocol">
              <span class="product_safety_protocol_icon">
                <img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/pficon.svg" />
              </span>Fast & free shipping
            </li>
          </ul>		
</div>
      </div>

    </div>          

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }




</script>
