<section class="my_account_pg">
<div class="main_container img_skeleton skeleton">
<div class="dashboard_content hide-div">
        <p>Hello John (not John? <a href="">Log out</a>)</p>
        <p>From your account dashboard you can view your <a href="orders.html">recent orders</a> , manage your <a href="addresses.html">shipping and billing addresses</a> , and edit your <a href="account-details.html">password and account
              details.</a> </p>

        </div>
    </div>
  </section>
