<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="wishlist_item_img">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" class="wishlist_item_img_child" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
        <?= $block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail')->toHtml() ?>
    </a>
</div>