<!---
          

          <ul class="shop_product_tab_label_wrap product_tab_wrapper skeleton">
            <li class="shop_product_tab_label_item hide-s-box">most popular</li>
            <li class="shop_product_tab_label_item hide-s-box">most rated</li>
            <li class="shop_product_tab_label_item hide-s-box">most popular</li>
            <li class="shop_product_tab_label_item hide-s-box">most popular</li>
          </ul>
          
          <ul class="shop_product_list_wrap product_card skeleton">
            <li class="shop_product_item">
              <div class="shop_product_item_img_wrap hide-img">
                <a href="product-detail.html">
                  <span class="shop_product_item_discount">-21%</span>
                  <img src="assets/img/prodimg.png" />
                </a>
                <button class="product_item_wishlist_btn">
                  <div class="wishlist">
                    <i class="far fa-heart"></i>
                  </div>
                  <div class="wishlisted">
                    <i class="fas fa-heart"></i>
                  </div>
                </button>
              </div>
              <a href="product-detail.html" class="shop_product_item_child">

                <h3 class="home_product_name hide-text">item 3896</h3>
                <div class="home_product_item_price hide-price-text">
                  <div class="home_product_item_actual_price ">AED 49,00</div>
                  <div class="home_product_item_sale_price ">AED 20.00</div>
                </div>
                <div class="home_product_item_save_amount hide-sub-text">save AED 29.00</div>

              </a>

            </li>
          </ul>
          
          <ul class="shop_product_list_wrap">
            <li class="shop_product_item">
              <div class="shop_product_item_img_wrap hide-img">
                <a href="product-detail.html">
                  <span class="shop_product_item_discount">-21%</span>
                  <img src="assets/img/prodimg.png" />
                </a>
                <button class="product_item_wishlist_btn">
                  <div class="wishlist">
                    <i class="far fa-heart"></i>
                  </div>
                  <div class="wishlisted">
                    <i class="fas fa-heart"></i>
                  </div>
                </button>
              </div>
              <a href="product-detail.html" class="shop_product_item_child">

                <h3 class="home_product_name hide-text">item 3896</h3>
                <div class="home_product_item_price hide-price-text">
                  <div class="home_product_item_actual_price ">AED 49,00</div>
                  <div class="home_product_item_sale_price ">AED 20.00</div>
                </div>
                <div class="home_product_item_save_amount hide-sub-text">save AED 29.00</div>

              </a>

            </li>
          </ul>
          
          <ul class="shop_product_list_wrap">
            <li class="shop_product_item">
              <div class="shop_product_item_img_wrap hide-img">
                <a href="product-detail.html">
                  <span class="shop_product_item_discount">-21%</span>
                  <img src="assets/img/prodimg.png" />
                </a>
                <button class="product_item_wishlist_btn">
                  <div class="wishlist">
                    <i class="far fa-heart"></i>
                  </div>
                  <div class="wishlisted">
                    <i class="fas fa-heart"></i>
                  </div>
                </button>
              </div>
              <a href="product-detail.html" class="shop_product_item_child">

                <h3 class="home_product_name hide-text">item 3896</h3>
                <div class="home_product_item_price hide-price-text">
                  <div class="home_product_item_actual_price ">AED 49,00</div>
                  <div class="home_product_item_sale_price ">AED 20.00</div>
                </div>
                <div class="home_product_item_save_amount hide-sub-text">save AED 29.00</div>

              </a>

            </li>
          </ul>
          
          <ul class="shop_product_list_wrap">
            <li class="shop_product_item">
              <div class="shop_product_item_img_wrap hide-img">
                <a href="product-detail.html">
                  <span class="shop_product_item_discount">-21%</span>
                  <img src="assets/img/prodimg.png" />
                </a>
                <button class="product_item_wishlist_btn">
                  <div class="wishlist">
                    <i class="far fa-heart"></i>
                  </div>
                  <div class="wishlisted">
                    <i class="fas fa-heart"></i>
                  </div>
                </button>
              </div>
              <a href="product-detail.html" class="shop_product_item_child">

                <h3 class="home_product_name hide-text">item 3896</h3>
                <div class="home_product_item_price hide-price-text">
                  <div class="home_product_item_actual_price ">AED 49,00</div>
                  <div class="home_product_item_sale_price ">AED 20.00</div>
                </div>
                <div class="home_product_item_save_amount hide-sub-text">save AED 29.00</div>

              </a>

            </li>
            <li class="shop_product_item">
              <div class="shop_product_item_img_wrap hide-img">
                <a href="product-detail.html">
                  <span class="shop_product_item_discount">-21%</span>
                  <img src="assets/img/prodimg.png" />
                </a>
                <button class="product_item_wishlist_btn">
                  <div class="wishlist">
                    <i class="far fa-heart"></i>
                  </div>
                  <div class="wishlisted">
                    <i class="fas fa-heart"></i>
                  </div>
                </button>
              </div>
              <a href="product-detail.html" class="shop_product_item_child">

                <h3 class="home_product_name hide-text">item 3896</h3>
                <div class="home_product_item_price hide-price-text">
                  <div class="home_product_item_actual_price ">AED 49,00</div>
                  <div class="home_product_item_sale_price ">AED 20.00</div>
                </div>
                <div class="home_product_item_save_amount hide-sub-text">save AED 29.00</div>

              </a> 

            </li>
          </ul>

-->
       