<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php

$_productCollection = $block->getLoadedProductCollection()->joinTable(
                    'cataloginventory_stock_item',
                    'product_id=entity_id',
                    ['qty'], // you can specify specific columns here
                    null,
                    'left'
                );
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');

$_helperStock = $this->helper(Basari\UploadForm\Helper\Data::class);

?>
<?php if (!$_productCollection->count()): ?>
    <div class="shop_product_wrapper ">
        <div class="product_coming_soon_wrapper img_skeleton skeleton">
            <div class="product_coming_soon_wrap hide-div mt-5">
                <div class="product_coming_soon_img"><img src="https://magento-920116-4739515.cloudwaysapps.com/media/theme/basari/comingsoon.svg" /></div>
                <div class="product_coming_soon_title">Coming  Soon</div>
            </div>
        </div>
    </div>
<?php else: ?>
    <?php //$block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="shop_product_wrapper">
        <ul class="shop_product_list_wrap product_card skeleton">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="shop_product_item">
                <div class="shop_product_item_img_wrap hide-img"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <span class="shop_product_item_discount">-21%</span>
                        <?= $productImage->toHtml() ?>
                    </a>
                    <button class="product_item_wishlist_btn">
                      <div class="wishlist">
                        <i class="far fa-heart"></i>
                      </div>
                      <div class="wishlisted">
                        <i class="fas fa-heart"></i>
                      </div>
                    </button>
                </div>
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                     
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                               <h3 class="home_product_name hide-text"><?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?></h3>
                            </a>
                            <?php if ($_product->isAvailable()) : ?>
                                    <div class="stock available">
                                       <span><?php 
                                        echo $_helperStock->getQty($_product->getSku()); ?>
                                        <?= $block->escapeHtml(__(' available')) ?></span></div>
                                <?php else : ?>
                                    <div class="stock unavailable">
                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                            <?php endif; ?> 
                        <?php //$block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                        <?php // $block->getProductDetailsHtml($_product) ?>

                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php echo $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>